[package]
name = "heatmap"
version = "1.0.0"
authors = ["Andrew Davis <pulpdrew@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.20.0"